### ISSUE TITLE
Error: does not support v0.6.3

### ISSUE THREAD

**Issue by Roger-luo** [yurivish/Hyperscript.jl#10]
I guess something is missed in `REQUIRE`? I got this when I try `Pkg.add`

```
ERROR: Hyperscript can't be installed because it has no versions that support 0.6.3 of julia. You may need to update METADATA by running `Pkg.update()`
```

**Comment by yurivish** [comment]
Hi Roger, Hyperscript is designed for 0.7/1.0. I’m waiting for the final pieces of the new package manager to shake out and then I’ll tag a release — but you can use the master branch now; the documentation in the readme reflects the latest functionality. 

Best!

**Comment by Roger-luo** [comment]
I see. Thanks! I'm just looking for something generates svg, I'll use it on 0.7 then.

**Comment by yurivish** [comment]
Ok! You might find this small utility function useful if you're exporting to a .svg (it adds the SVG header): https://github.com/yurivish/Hyperscript.jl/blob/master/src/Hyperscript.jl#L508

I found myself using it frequently so I added it to the library but haven't documented it since I'm not sure this is the best design for a function like that.

**Comment by Roger-luo** [comment]
@yurivish Thanks a lot! I'll keep your guys update if I meet any problem or I get any idea for this package. I'll try to use your package to generate SVG diagrams.
